### ISSUE TITLE
Add ES6 Decorator support

### ISSUE THREAD

**Issue by udnisap** [udnisap/debuk#3]
Support debuk to be used like using ES6 Decorators 

```
@debuk(options)
myfunction(){

}
```

**Comment by alhimik45** [comment]
Is this feature should be as separate function like `debukDecorator` or you want `debuk` could be used in both way like a decorator and like a function. I think second variant cannot be done without breaking backward compatibility.

**Comment by udnisap** [comment]
I was thinking more of the second approach. But we can import the decorator as a different import. 
@alhimik45 I didnt quite understand the complexity that would break the backward compatibility. Can you explain bit more?

**Comment by alhimik45** [comment]
Now `debuk` takes two arguments: `(fn, options = {})` and works for both classes and functions.
ES class decorators takes one argument: `target`, and property decorators takes three arguments: `target, key, descriptor`, so we need some logic with arguments number and arguments types to determine in what case `debuk` is called.
If you agree to such kind of solution, i'll do it tomorrow

**Comment by udnisap** [comment]
Lets have a logic (possibly from a different package) to determine which one is called and return the same effect. for all of the above. please make sure that this multiplexing logic is not part of the main code. 
I am suggesting
- [ ] a landing function which determines the use case and call the appropriate implementation. 
- [ ] implementation for class decorators
- [ ] implementation for property decorators
- [ ] tests

**Comment by udnisap** [comment]
Fixed with #7
