### ISSUE TITLE
Add support for ES6 Classes

### ISSUE THREAD

**Issue by udnisap** [udnisap/debuk#4]
Add Debuk  to all instances of a given constructor and support ES6 classes.

```
Class OriginalPerson {
  constructor(name){
    this.name = name;
  } 

  speak(words){
    return `${this.name}: ${words}`;
  }
}
const Person = Debuk(OriginalPerson, {params: true});
const p1 = new Person('Tom');
p1.speak('test'); 
// OriginalPerson speak: params 'test' => 'Tom: test'

```

**Comment by fdiogo** [comment]
Hey! First timer here on open-source. I would like to try this out. Could I claim this issue?

**Comment by tpai** [comment]
Send you PR, have a check. :)
https://github.com/udnisap/debuk/pull/6

**Comment by udnisap** [comment]
Thanks for your contribution. Once the PR is merged it will auto release.
